name: spo2_monitor
description: A simple Flutter app for SpO2 monitoring and history tracking.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  path_provider: ^2.0.15
  flutter_blue_plus: ^1.30.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_thingspeak: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
